
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  phone_number: 'phone_number',
  avatar_url: 'avatar_url',
  role: 'role',
  status: 'status',
  last_login: 'last_login',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Admin_userScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  role: 'role',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  cover_image_url: 'cover_image_url',
  is_visible: 'is_visible',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  title: 'title',
  name: 'name',
  sku: 'sku',
  description_short: 'description_short',
  description_long: 'description_long',
  price: 'price',
  sale_price: 'sale_price',
  compare_at_price: 'compare_at_price',
  cover_image_url: 'cover_image_url',
  hover_image_url: 'hover_image_url',
  image_url_list: 'image_url_list',
  stock_quantity: 'stock_quantity',
  available_sizes: 'available_sizes',
  available_colors: 'available_colors',
  material_info: 'material_info',
  care_instructions: 'care_instructions',
  size_chart_url: 'size_chart_url',
  status: 'status',
  category_id: 'category_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  subtotal_price: 'subtotal_price',
  total_price: 'total_price',
  shipping_fee: 'shipping_fee',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Cart_itemScalarFieldEnum = {
  id: 'id',
  cart_id: 'cart_id',
  product_id: 'product_id',
  quantity: 'quantity',
  unit_price: 'unit_price',
  selected_size: 'selected_size',
  selected_color: 'selected_color',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  order_number: 'order_number',
  user_id: 'user_id',
  status: 'status',
  payment_method: 'payment_method',
  total_amount: 'total_amount',
  total_price: 'total_price',
  shipping_fee: 'shipping_fee',
  shipping_name: 'shipping_name',
  shipping_phone: 'shipping_phone',
  shipping_address: 'shipping_address',
  shipping_city: 'shipping_city',
  tracking_number: 'tracking_number',
  refund_reason: 'refund_reason',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Order_itemScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  product_id: 'product_id',
  product_title: 'product_title',
  product_cover_image_url: 'product_cover_image_url',
  quantity: 'quantity',
  unit_price: 'unit_price',
  price_at_purchase: 'price_at_purchase',
  selected_size: 'selected_size',
  selected_color: 'selected_color',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.User_addressScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  recipient_name: 'recipient_name',
  phone_number: 'phone_number',
  address_line_1: 'address_line_1',
  address_line_2: 'address_line_2',
  city: 'city',
  postal_code: 'postal_code',
  zip_code: 'zip_code',
  is_default: 'is_default',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  user_id: 'user_id',
  user_name: 'user_name',
  rating_value: 'rating_value',
  comment_text: 'comment_text',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PromotionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  background_image_url: 'background_image_url',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.userOrderByRelevanceFieldEnum = {
  username: 'username',
  email: 'email',
  password: 'password',
  phone_number: 'phone_number',
  avatar_url: 'avatar_url'
};

exports.Prisma.admin_userOrderByRelevanceFieldEnum = {
  username: 'username',
  email: 'email',
  password: 'password'
};

exports.Prisma.categoryOrderByRelevanceFieldEnum = {
  name: 'name',
  slug: 'slug',
  description: 'description',
  cover_image_url: 'cover_image_url'
};

exports.Prisma.productOrderByRelevanceFieldEnum = {
  title: 'title',
  name: 'name',
  sku: 'sku',
  description_short: 'description_short',
  description_long: 'description_long',
  cover_image_url: 'cover_image_url',
  hover_image_url: 'hover_image_url',
  image_url_list: 'image_url_list',
  available_sizes: 'available_sizes',
  available_colors: 'available_colors',
  material_info: 'material_info',
  care_instructions: 'care_instructions',
  size_chart_url: 'size_chart_url'
};

exports.Prisma.cart_itemOrderByRelevanceFieldEnum = {
  selected_size: 'selected_size',
  selected_color: 'selected_color'
};

exports.Prisma.orderOrderByRelevanceFieldEnum = {
  order_number: 'order_number',
  shipping_name: 'shipping_name',
  shipping_phone: 'shipping_phone',
  shipping_address: 'shipping_address',
  shipping_city: 'shipping_city',
  tracking_number: 'tracking_number',
  refund_reason: 'refund_reason'
};

exports.Prisma.order_itemOrderByRelevanceFieldEnum = {
  product_title: 'product_title',
  product_cover_image_url: 'product_cover_image_url',
  selected_size: 'selected_size',
  selected_color: 'selected_color'
};

exports.Prisma.user_addressOrderByRelevanceFieldEnum = {
  recipient_name: 'recipient_name',
  phone_number: 'phone_number',
  address_line_1: 'address_line_1',
  address_line_2: 'address_line_2',
  city: 'city',
  postal_code: 'postal_code',
  zip_code: 'zip_code'
};

exports.Prisma.reviewOrderByRelevanceFieldEnum = {
  user_name: 'user_name',
  comment_text: 'comment_text'
};

exports.Prisma.promotionOrderByRelevanceFieldEnum = {
  title: 'title',
  subtitle: 'subtitle',
  background_image_url: 'background_image_url'
};
exports.user_role = exports.$Enums.user_role = {
  customer: 'customer',
  admin: 'admin',
  super_admin: 'super_admin'
};

exports.user_status = exports.$Enums.user_status = {
  active: 'active',
  suspended: 'suspended',
  deleted: 'deleted'
};

exports.product_status = exports.$Enums.product_status = {
  active: 'active',
  inactive: 'inactive',
  out_of_stock: 'out_of_stock'
};

exports.order_status = exports.$Enums.order_status = {
  pending: 'pending',
  confirmed: 'confirmed',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
  refunded: 'refunded'
};

exports.payment_method = exports.$Enums.payment_method = {
  cash_on_delivery: 'cash_on_delivery',
  credit_card: 'credit_card',
  bank_transfer: 'bank_transfer'
};

exports.Prisma.ModelName = {
  user: 'user',
  admin_user: 'admin_user',
  category: 'category',
  product: 'product',
  cart: 'cart',
  cart_item: 'cart_item',
  order: 'order',
  order_item: 'order_item',
  user_address: 'user_address',
  review: 'review',
  promotion: 'promotion'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
